//! Cross-language parity test against ganim's sga.hpp.
//!
//! Loads `tests/fixtures/pga3_cayley.json` (generated by the C++ harness in
//! the same directory) and asserts every record matches what
//! `rotorlab_ga::blade::blade_product_sign` and `blade_product_blade` produce.

use rotorlab_ga::Algebra;
use rotorlab_ga::blade::{blade_product_blade, blade_product_sign};
use rotorlab_ga::pga3::Pga3;
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct CayleyEntry {
    i: u64,
    j: u64,
    sign: i32,
    blade: u64,
}

fn fixture_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests");
    p.push("fixtures");
    p.push("pga3_cayley.json");
    p
}

#[test]
fn pga3_cayley_matches_ganim() {
    let path = fixture_path();
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "fixture {} not found: {e}. Run `cd tests/fixtures && make` to generate it.",
            path.display()
        )
    });
    let entries: Vec<CayleyEntry> = serde_json::from_slice(&bytes).expect("valid JSON");
    assert_eq!(entries.len(), 256, "fixture should have 16*16 entries");

    for e in &entries {
        let our_sign = blade_product_sign(e.i, e.j, Pga3::METRIC) as i32;
        let our_blade = blade_product_blade(e.i, e.j);
        assert_eq!(
            our_sign, e.sign,
            "sign mismatch at (i={}, j={}): ours={}, ganim={}",
            e.i, e.j, our_sign, e.sign
        );
        assert_eq!(
            our_blade, e.blade,
            "blade mismatch at (i={}, j={}): ours={}, ganim={}",
            e.i, e.j, our_blade, e.blade
        );
    }
}
